# Generated by Django 4.2.5 on 2023-09-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_archivo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='nombre_original',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
